name: dartgrad
description: Neural net library, made for learning purposes, inspired by micrograd.
version: 1.0.2
repository: https://github.com/Descrout/dartgrad

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
